stages:
  - build
  - test

build:
  stage: build
  image: maven:3.8.1-openjdk-17-slim
  script:
    - export NEW_VERSION=${CI_COMMIT_SHA:0:8}-${CI_COMMIT_REF_NAME}
    - cd gps_g22 #change directory to project
    - mvn versions:set -DnewVersion=1-$NEW_VERSION
    - mvn -s ci_settings.xml deploy
  only:
    - ga
    - main

unit-test-job:   # This job runs in the test stage.
  image: maven:3.8.4-openjdk-17-slim
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cd gps_g22 #change directory to project
    - echo "Running unit tests…"
    - mvn test


variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
sonarcloud-check:
  image: maven:3-openjdk-17
  stage: test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd gps_g22 #change directory to project
    - mvn verify sonar:sonar -Dsonar.projectKey=gps_g221_mybudget
